from django.db import models
from .choices import *
from django.contrib.auth.models import User
#import forms
# Create your models here.

class Ficha(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    data = models.DateField(null=True, blank=True)
    nome = models.CharField(max_length=100, blank=True)
    dn = models.DateField(null=True, blank=True)
    sexo = models.CharField(choices=SEXO_CHOICES, blank=True, max_length=10, default="0")
    cpf = models.CharField(max_length=30, blank=True)
    hosp = models.CharField(max_length=50, blank=True)
    convenio = models.CharField(max_length=30, blank=True)
    cirurgia = models.CharField(max_length=100, blank=True)
    cirurgiao = models.CharField(max_length=50, blank=True)

    peso = models.DecimalField(decimal_places=1, max_digits=5, null=True, blank=True)
    altura = models.DecimalField(decimal_places=0, max_digits=5, null=True, blank=True)
    imc = models.DecimalField(decimal_places=2, max_digits=5, null=True, blank=True)

    n_previa = models.BooleanField(default=True)
    c_previa = models.CharField(max_length=100, blank=True)
    a_previa = models.CharField(max_length=100, blank=True)
    n_adversos = models.BooleanField(default=True)
    adversos = models.CharField(max_length=100, blank=True)

    mets = models.CharField(choices=METS_CHOICES, blank=True, max_length=20, default="1")
    cardio_neg = models.BooleanField(default=True)
    cardio_has = models.BooleanField(default=False)
    cardio_arr = models.BooleanField(default=False)
    cardio_cor = models.BooleanField(default=False)
    cardio_icc = models.BooleanField(default=False)
    cardio_out = models.BooleanField(default=False)
    neuro_neg = models.BooleanField(default=True)
    neuro_avc = models.BooleanField(default=False)
    neuro_cef = models.BooleanField(default=False)
    neuro_con = models.BooleanField(default=False)
    neuro_lme = models.BooleanField(default=False)
    neuro_out = models.BooleanField(default=False)
    resp_neg = models.BooleanField(default=True)
    resp_asm = models.BooleanField(default=False)
    resp_dpo = models.BooleanField(default=False)
    resp_tbg = models.BooleanField(default=False)
    resp_iva = models.BooleanField(default=False)
    resp_out = models.BooleanField(default=False)
    gastro_neg = models.BooleanField(default=True)
    gastro_rge = models.BooleanField(default=False)
    gastro_gas = models.BooleanField(default=False)
    gastro_vom = models.BooleanField(default=False)
    gastro_obs = models.BooleanField(default=False)
    gastro_out = models.BooleanField(default=False)
    endocrino_neg = models.BooleanField(default=True)
    endocrino_dia = models.BooleanField(default=False)
    endocrino_dti = models.BooleanField(default=False)
    endocrino_dlp = models.BooleanField(default=False)
    endocrino_out = models.BooleanField(default=False)
    renal_neg = models.BooleanField(default=True)
    renal_irc = models.BooleanField(default=False)
    renal_ira = models.BooleanField(default=False)
    renal_dia = models.BooleanField(default=False)
    renal_out = models.BooleanField(default=False)
    hem_neg = models.BooleanField(default=True)
    hem_coa = models.BooleanField(default=False)
    hem_ane = models.BooleanField(default=False)
    hem_tra = models.BooleanField(default=False)
    hem_hep = models.BooleanField(default=False)
    hem_hiv = models.BooleanField(default=False)
    hem_out = models.BooleanField(default=False)
    musc_neg = models.BooleanField(default=True)
    musc_lom = models.BooleanField(default=False)
    musc_des = models.BooleanField(default=False)
    musc_ati = models.BooleanField(default=False)
    musc_ato = models.BooleanField(default=False)
    musc_dis = models.BooleanField(default=False)
    musc_out = models.BooleanField(default=False)

    medicacoes = models.CharField(max_length=300, blank=True)
    medicacoes2 = models.CharField(max_length=300, blank=True)
    alergias = models.CharField(max_length=200, blank=True, default=default['alergias'])
    geral = models.CharField(max_length=100, blank=True, default=default['geral'])
    acv = models.CharField(max_length=100, blank=True, default=default['acv'])
    ar = models.CharField(max_length=100, blank=True, default=default['ar'])
    abd = models.CharField(max_length=100, blank=True, default=default['abd'])
    ext = models.CharField(max_length=100, blank=True, default=default['ext'])
    pas = models.IntegerField(default=0)
    pad = models.IntegerField(default=0)
    fc = models.IntegerField(default=0)
    fr = models.IntegerField(default=0)
    temp = models.CharField(max_length=10, blank=True, default=default['temp'])

    mallampati = models.CharField(choices=mallampati_CHOICES, blank=True, max_length=20)
    distem = models.CharField(choices=distem_CHOICES, blank=True, max_length=20)
    mobcer = models.CharField(choices=mobcer_CHOICES, blank=True, max_length=20)
    aboral = models.CharField(choices=aboral_CHOICES, blank=True, max_length=20)
    protese = models.CharField(choices=protese_CHOICES, blank=True, max_length=20)
    vad = models.CharField(choices=vad_CHOICES, blank=True, max_length=20)

    hb = models.DecimalField(decimal_places=1, max_digits=8, null=True, blank=True)
    ht = models.DecimalField(decimal_places=1, max_digits=8, null=True, blank=True)
    leuco = models.DecimalField(decimal_places=0, max_digits=8, null=True, blank=True)
    plt = models.DecimalField(decimal_places=0, max_digits=8, null=True, blank=True)
    gli = models.DecimalField(decimal_places=1, max_digits=8, null=True, blank=True)
    u = models.DecimalField(decimal_places=1, max_digits=8, null=True, blank=True)
    cr = models.DecimalField(decimal_places=2, max_digits=8, null=True, blank=True)
    na = models.DecimalField(decimal_places=1, max_digits=8, null=True, blank=True)
    k = models.DecimalField(decimal_places=2, max_digits=8, null=True, blank=True)
    ts = models.DecimalField(decimal_places=2, max_digits=8, null=True, blank=True)
    tc = models.DecimalField(decimal_places=2, max_digits=8, null=True, blank=True)
    inr = models.DecimalField(decimal_places=2, max_digits=8, null=True, blank=True)
    tp = models.DecimalField(decimal_places=2, max_digits=8, null=True, blank=True)
    ttpa = models.DecimalField(decimal_places=2, max_digits=8, null=True, blank=True)

    ecg = models.CharField(max_length=200, blank=True)
    eco = models.CharField(max_length=200, blank=True)
    rx = models.CharField(max_length=200, blank=True)
    ergo = models.CharField(max_length=200, blank=True)
    outroex = models.CharField(max_length=200, blank=True)
    anotacoes = models.CharField(max_length=200, blank=True)
    anotacoes2 = models.CharField(max_length=200, blank=True)
    proposta = models.CharField(max_length=200, blank=True)
    jejum = models.CharField(max_length=200, blank=True)
    prescricao = models.CharField(max_length=200, blank=True)
    prescricao2 = models.CharField(max_length=200, blank=True)
    prescricao3 = models.CharField(max_length=200, blank=True)
    asa = models.PositiveSmallIntegerField(default=1, blank=True)


    def __str__(self):
        return self.nome

