# Generated by Django 2.0.5 on 2018-05-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=100)),
                ('dn', models.DateField()),
                ('cpf', models.CharField(max_length=30)),
                ('hosp', models.CharField(max_length=50)),
                ('convenio', models.CharField(max_length=30)),
                ('cirurgia', models.CharField(max_length=100)),
                ('cirurgiao', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
