# Generated by Django 2.0.5 on 2018-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cirurgia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cirurgiao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='convenio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cpf',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='dn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='hosp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
