# Generated by Django 2.0.5 on 2018-05-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_auto_20180525_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10),
        ),
    ]
