# Generated by Django 2.0.5 on 2018-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_ficha_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='imc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='sexo',
            field=models.CharField(blank=True, choices=[('0', 'Desconhecido'), ('1', 'Masculino'), ('2', 'Feminino'), ('9', 'Não se aplica')], default='0', max_length=10),
        ),
    ]
