# Generated by Django 2.0.5 on 2018-05-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_auto_20180525_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='aprevia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ficha',
            name='cprevia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ficha',
            name='nprevia',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
