# Generated by Django 2.0.5 on 2018-05-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_auto_20180525_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='nprevia',
            field=models.BooleanField(default=True),
        ),
    ]
