# Generated by Django 2.0.5 on 2018-05-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0007_auto_20180531_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='nprevia',
            field=models.BooleanField(default=True),
        ),
    ]
