# Generated by Django 2.0.5 on 2018-06-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0009_auto_20180531_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='aprevia',
            new_name='a_previa',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='cprevia',
            new_name='adversos',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='nprevia',
            new_name='n_adversos',
        ),
        migrations.AddField(
            model_name='ficha',
            name='c_previa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ficha',
            name='n_previa',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
