# Generated by Django 2.0.5 on 2018-06-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0011_auto_20180601_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='mets',
            field=models.CharField(blank=True, choices=[('0', 'Impossível Avaliar'), ('1', 'Maior que 4 mets'), ('2', 'Menos que 4 mets')], default='0', max_length=10),
        ),
    ]
