# Generated by Django 2.0.5 on 2018-06-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0012_ficha_mets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='mets',
            field=models.CharField(blank=True, choices=[('0', 'Impossível Avaliar'), ('1', 'Maior que 4 mets'), ('2', 'Menor que 4 mets')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='n_previa',
            field=models.NullBooleanField(),
        ),
    ]
