# Generated by Django 2.0.5 on 2018-06-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0014_auto_20180601_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='n_previa',
            field=models.BooleanField(default=False),
        ),
    ]
