# Generated by Django 2.0.5 on 2018-06-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0016_auto_20180601_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='cardio_neg',
            field=models.BooleanField(default=True),
        ),
    ]
