# Generated by Django 2.0.5 on 2018-06-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0019_ficha_medicacoes2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='aboral',
            field=models.CharField(blank=True, choices=[('0', 'Desconhecido'), ('1', 'Maior que 4cm'), ('2', 'Menor que 4cm')], max_length=20),
        ),
        migrations.AddField(
            model_name='ficha',
            name='distem',
            field=models.CharField(blank=True, choices=[('0', 'Desconhecido'), ('1', 'Maior que 12cm'), ('2', 'Menor que 12cm')], max_length=20),
        ),
        migrations.AddField(
            model_name='ficha',
            name='mallampati',
            field=models.CharField(blank=True, choices=[('0', 'Desconhecido'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20),
        ),
        migrations.AddField(
            model_name='ficha',
            name='mobcer',
            field=models.CharField(blank=True, choices=[('0', 'Desconhecido'), ('1', 'Boa'), ('2', 'Limitada')], max_length=20),
        ),
        migrations.AddField(
            model_name='ficha',
            name='protese',
            field=models.CharField(blank=True, choices=[('0', 'Desconhecido'), ('1', 'Não'), ('2', 'Sim')], max_length=20),
        ),
        migrations.AddField(
            model_name='ficha',
            name='vad',
            field=models.CharField(blank=True, choices=[('0', 'Desconhecido'), ('1', 'Não'), ('2', 'Sim')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='mets',
            field=models.CharField(blank=True, choices=[('0', 'Desconhecido'), ('1', 'Maior que 4 mets'), ('2', 'Menor que 4 mets'), ('9', 'Impossível Avaliar')], max_length=20),
        ),
    ]
