# Generated by Django 2.0.5 on 2018-06-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0020_auto_20180602_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='cr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='gli',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='hb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ht',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='inr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='leuco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='na',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='plt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ttpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='u',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
