# Generated by Django 2.0.5 on 2018-06-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0021_auto_20180602_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='anotacoes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='anotacoes2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='asa',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ecg',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='eco',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ergo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='jejum',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='outroex',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='prescricao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='prescricao2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='prescricao3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='proposta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='rx',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
