# Generated by Django 2.0.5 on 2018-06-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0022_auto_20180603_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='asa',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
