# Generated by Django 2.0.5 on 2018-06-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0023_auto_20180603_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='abd',
            field=models.CharField(blank=True, default='N.D.N.', max_length=100),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='acv',
            field=models.CharField(blank=True, default='BULHAS RÍTMICAS, NORMOFONÉTICAS, EM DOIS TEMPOS, SEM SOPROS', max_length=100),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='alergias',
            field=models.CharField(blank=True, default='DESCONHECE ALERGIAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='ar',
            field=models.CharField(blank=True, default='MURMÚRIOS VESICULARES PRESENTES BILATERALMENTE, SEM RUÍDOS ADVENTÍCIOS', max_length=100),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='ext',
            field=models.CharField(blank=True, default='N.D.N.', max_length=100),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='geral',
            field=models.CharField(blank=True, default='BEG, L.O.T.E., EUPNEICO, NORMOCORADO, HIDRATADO', max_length=100),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='mets',
            field=models.CharField(blank=True, choices=[('0', 'Desconhecido'), ('1', 'Maior que 4 mets'), ('2', 'Menor que 4 mets'), ('9', 'Impossível Avaliar')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='n_adversos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='temp',
            field=models.CharField(blank=True, default='AFEBRIL', max_length=10),
        ),
    ]
