# Generated by Django 2.0.5 on 2018-06-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0027_auto_20180622_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='medico',
            new_name='user',
        ),
    ]
