# Generated by Django 2.0.5 on 2018-06-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0028_auto_20180622_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
